### ISSUE TITLE
Unable to open menu on Xbox One

### ISSUE THREAD

**Issue by matty0** [Aftnet/RetriX#13]
I have tried all buttons and all combo's I can think of but can't trigger the menu on the xbox

This compounds the other issue I will raise about the inability to save.

Thanks!

**Comment by dominater01** [comment]
press both start and select at the same time to popup the save menu if not press and hold select b4 start and it should popup

**Comment by albertofustinoni** [comment]
As Dominater says, select then start while still pressing select is how you bring the menu up.
