### ISSUE TITLE
Crackling sound in Snes core - 2.0.4.0 on Xbox One

### ISSUE THREAD

**Issue by Azy77** [Aftnet/RetriX#15]
Although the sound quality seems to sound clearer than v 1.9.40 after a while there is crackling. Tested on Aliens 3.

The crackling comes and goes throughout the game.

**Comment by dominater01** [comment]
can confirm this is still happening on 2.1.0.0

**Comment by albertofustinoni** [comment]
You may want to open a ticket on Snes9X’s GitHub page for this.
https://github.com/libretro/snes9x

**Comment by Azy77** [comment]
Just tried snes on 2.1.0.0. and for me the crackling is not there, however some sounds start to mute out after a few mins. E.g. all weapon sounds on Aliens 3. 

Does this need to be raised on the snes9x link above?

**Comment by albertofustinoni** [comment]
If only some sounds then yes, raise it on the other repo
