### ISSUE TITLE
Some FBA roms have a blank screen

### ISSUE THREAD

**Issue by Azy77** [Aftnet/RetriX#16]
Games like Super Street Fighter 2 and Shadow Dancer have a blank screen. This is the case in all Retrix builds.

**Comment by dominater01** [comment]
fba doesnt have perfect support it only plays what the fba core from retroarch can play

**Comment by Azy77** [comment]
The same Shadow dancer loads fine on fba retroarch. Tested on wii retroarch.

**Comment by dominater01** [comment]
i assume theres different cores for fba like mame (if not nevermind) so maybe he's using a different core idk

**Comment by Querpmuerp** [comment]
Please try it with fba 2.97.42 romset, this is the version of FBA Retrix uses.
I could get all CPS2 games to work that way.

**Comment by Azy77** [comment]
Ok mate will give that a shot and report back later in week.

**Comment by Azy77** [comment]
Just tried 2.97.42 rom version and same thing. Can you confirm you tried SSF2 in your CPS2 test?

**Comment by Querpmuerp** [comment]
I got a one s. I never have to uninstall Retrix, only for updating to a newer version. Sometimes Retrix crashes in the FBA core when hitting pause, but after force quitting Retrix and opening it again it works fine.
