### ISSUE TITLE
Xbox One error during install 

### ISSUE THREAD

**Issue by tylerhoot** [Aftnet/RetriX#22]
error that is happening is below 
Installation Progress
Failure reason: Windows cannot install package 15612Aftnet.RetriX_2.1.0.0_x64__tw8pheqffcq7j because this package depends on a framework that could not be found. Provide the framework "Microsoft.NET.Native.Framework.2.1" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 2.1.26424.0, along with this package to install. The frameworks with name "Microsoft.NET.Native.Framework.2.1" currently installed are: {} Failure text: Package failed updates, dependency or conflict validation. (0x80073cf3)

**Comment by dominater01** [comment]
you need to install the dependencies aswell

**Comment by tylerhoot** [comment]
how would i go about getting the dependencies

**Comment by dominater01** [comment]
https://github.com/Aftnet/RetriX/releases

click on dependencies.zip for the version you have

**Comment by tylerhoot** [comment]
fixed thanks
