### ISSUE TITLE
Error during installing to XBOX ONE

### ISSUE THREAD

**Issue by tibordoma** [Aftnet/RetriX#28]
It is more a question than issue.

When I try to install the package to game console, the error appears:
Failure reason: Windows cannot install package 15612Aftnet.RetriX_2.1.1.0_x64__tw8pheqffcq7j because this package depends on a framework that could not be found. Provide the framework "Microsoft.NET.Native.Framework.2.1" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 2.1.26424.0, along with this package to install. The frameworks with name "Microsoft.NET.Native.Framework.2.1" currently installed are: {} Failure text: Package failed updates, dependency or conflict validation. (0x80073cf3)

Where can I obtain this dependency? Thank you.
It should be added to your guide: https://github.com/Aftnet/RetriX/wiki/Sideloading-on-Xbox-One

**Comment by Ehkad** [comment]
https://github.com/aftnet/retrix/releases

**Comment by albertofustinoni** [comment]
If you go to the releases pages, each of them has a dependencies zip. Use the ones in the x64 folder of the archive
