### ISSUE TITLE
2.0.1.0 Not starting on Lumia 950XL

### ISSUE THREAD

**Issue by DoogeJ** [Aftnet/RetriX#3]
Hi!

I'm using a Microsoft Lumia 950XL and managed to install the application, but it won't run/start.

Tapping the application in my menu makes my display go black for a second, and then return to the menu.

Is there any place where I can look for a log file or something?

Edit: Using 2.0.1.0

**Comment by DoogeJ** [comment]
I just tried 1.9.4.0 and it works! I'm glad to keep testing newer builds tho.

**Comment by DoogeJ** [comment]
No problem, let me know what to test :+1:

**Comment by albertofustinoni** [comment]
Should be fixed in 2.0.3

**Comment by WiNG-CoMM** [comment]
@DoogeJ what did you do to be able to install it?
My Lumia 950XL is on version 10.0.15254.490, trying to install RetriX 2.1.1.0 and nothing ever happens. It never seems to install at all. I tried to install the dependencies separately with no success as well. Never gives me any kind of error or anything, it just never seem to install

**Comment by albertofustinoni** [comment]
As of 2.1.0 RetriX requires Windows 10 Fall Creators Update or later, which unfortunately means no phones :(

I have a 950 myself and it hurt me to do so, but staying on CU alone was not tenable anymore.

**Comment by WiNG-CoMM** [comment]
Oh, shame. 2.0 should still be working then?

**Comment by DoogeJ** [comment]
@WiNG-CoMM I believe 2.0.4 is the most recent version that should work on phones: https://github.com/Aftnet/RetriX/releases/tag/RetriX_2.0.4

**Comment by WiNG-CoMM** [comment]
Testing it now, works flawlessly for what I intended - couple of GBA games on bus rides. Thanks guys
