### ISSUE TITLE
Error on deploy - a certificate was explicitly revoked by its issuer

### ISSUE THREAD

**Issue by alsandri** [Aftnet/RetriX#38]
Hi, 

When I try deploy "RetriX.UWP_2.1.1.0_x86_x64_arm.appxbundle" in my xbox one, I get the error "A certificate was explicitly revoked by its issuer. (0x800B010C)".

Can you help me?

Thank you!
![error](https://user-images.githubusercontent.com/48334361/53988553-821a1c00-4102-11e9-9350-c0c28ce50250.jpeg)

**Comment by dominater01** [comment]
did you login to dev mode with your xbl account?

**Comment by hdelvalle009** [comment]
@dominater01 Hello guys, I have a problem regarding the installation, can you help me?

**Comment by KickNsticks** [comment]
I'm getting this same error message. I am signed into xbox live on Dev Mode. I select the package then the x64 dependencies.

**Comment by dominater01** [comment]
the pic says no users registered thats why i said you have to login to your xbl account from the dev home menu where it says add account

**Comment by moewe** [comment]
I have the same error message here, the xbl account is logged in.

**Comment by jaundice** [comment]
I get the same, logged in with dev user

**Comment by dominater01** [comment]
sry guys this error has already been mentioned by the dev and he said it would cost 100+ $ to fix this issue because the certificate costs that much now so i dont think this will get fixed anytime soon

**Comment by deershoot3r** [comment]
Having this same exact issue, currently signed in correctly. Tried with dependencies and without.

**Comment by Grimreaper86** [comment]
Damn! This emulator system is my only hope for this Windows 10 Phone. I hope they figure out the certificate issue soon. They should start a Patreon or something.

**Comment by AnthroHeader** [comment]
Fixed in latest build using a self signed certificate: while this allows installing RetriX again, it does require installing the cert at
https://github.com/Aftnet/RetriX/raw/master/RetriX.UWP/SigningCert_Release.cer in the machine (not user)'s "Trusted People" certificate store. This only needs to be done once.

**Comment by jensenjk** [comment]
Seems microsoft releases software which has a revoked certiticate attached
