### ISSUE TITLE
Xbox one installation

### ISSUE THREAD

**Issue by asemore** [Aftnet/RetriX#39]
I get the following error when sideloading on xbox

Installation Progress
Failure reason: Deployment Add operation with target volume D: on Package 15612Aftnet.RetriX_2.1.1.0_neutral_~_tw8pheqffcq7j from: (RetriX.UWP_2.1.1.0_x86_x64_arm%20(1).appxbundle) failed with error 0x800B010C. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. Failure text: A certificate was explicitly revoked by its issuer. (0x800b010c)

any ideas?

**Comment by dominater01** [comment]
i know this is for retrix but why not just use retroarch for xbox one? you can find it at bit.ly/xb1home

**Comment by asemore** [comment]
there isn't a version for xbox one

**Comment by asemore** [comment]
> there isn't a version for xbox one



> i know this is for retrix but why not just use retroarch for xbox one? you can find it at bit.ly/xb1home

But there isn't a version for xbox one!

**Comment by dominater01** [comment]
http://www.mediafire.com/file/sxka3kas8dcirce/Unofficial_RetroArch_1.7.6_Build_9_%2528Xbox_One%2529.7z/file

**Comment by dominater01** [comment]
always check bit.ly/xb1emu this link has an xbox one database for everything xbox one

**Comment by albertofustinoni** [comment]
With regards to the original bug: this is because [Microsoft has revoked Startcom’ CA certificate](https://www.microsoft.com/security/blog/2017/08/08/microsoft-to-remove-wosign-and-startcom-certificates-in-windows-10/)

Unfortunately the only real solution is to buy another certificate at 100+ USD per year :(

**Comment by asemore** [comment]
> always check bit.ly/xb1emu this link has an xbox one database for everything xbox one
please check link as this brings me to a cadillac page:)

> Unfortunately the only real solution is to buy another certificate at 100+ USD per year :(
Thanks for the info Albert.

**Comment by dominater01** [comment]
sorry i dont know why i put bit.ly/xb1emu i guess i wasnt thinking i meant bit.ly/xb1home

**Comment by asemore** [comment]
Thanks

> sorry i dont know why i put bit.ly/xb1emu i guess i wasnt thinking i meant bit.ly/xb1home
thanks dominater01

One more question:
Is it safe?

**Comment by dominater01** [comment]
sry i know i messed up and it looks sketchy so heres the link it goes to

http://www.mediafire.com/folder/f2wf0t8eqm7j3/All_Xbox_One_Homebrew

**Comment by asemore** [comment]
thanks dominater
is there a tutorial/how to about this?

**Comment by dominater01** [comment]
https://www.youtube.com/watch?v=M1c5PNv8SNc

**Comment by asemore** [comment]
> https://www.youtube.com/watch?v=M1c5PNv8SNc
great dominater01:) thanks for all your help, it works!
I have another question.
Is there not a mame emulator where I could load my roms?

**Comment by asemore** [comment]
@dominater01 
dont bother I saw your other youtube videos (subscribed) and I got my answer
Thank you so much

**Comment by dominater01** [comment]
glad i could help :)
