### ISSUE TITLE
Using the Nintendo DS touchscreen on Windows Phone (1.9.4.0)

### ISSUE THREAD

**Issue by DoogeJ** [Aftnet/RetriX#4]
Hi!

How do I use the DS touchscreen on my phone? Taps dont seem to get forwarded.

**Comment by albertofustinoni** [comment]
You cannot. That feature is not implemented right now.

**Comment by DoogeJ** [comment]
Why close this, and not flag it as future enhancement?

**Comment by AnthroHeader** [comment]
Phone support is not feasible anymore, closing this
